import { ENVELOPES } from "./physics.js";
import { createReceipt } from "./receipt.js";
import { didKeyFromPublicKey, generateKeyPair, type KeyPair } from "./keys.js";
import { merkleRoot } from "./merkle.js";
import { POO_VERSION, type Receipt, type ReceiptBundle, type ReceiptContext, type TaskClass } from "./types.js";

/** Small deterministic PRNG (mulberry32) so simulated days are reproducible. */
export function mulberry32(seed: number): () => number {
  let t = seed >>> 0;
  return () => {
    t = (t + 0x6d2b79f5) >>> 0;
    let x = Math.imul(t ^ (t >>> 15), t | 1);
    x ^= x + Math.imul(x ^ (x >>> 7), x | 61);
    return ((x ^ (x >>> 14)) >>> 0) / 4294967296;
  };
}

export interface SimulateOptions {
  /** Deterministic seed (also seeds the machine key if `keys` not supplied). */
  seed?: number;
  keys?: KeyPair;
  taskClass?: TaskClass;
  /** Number of daily epochs to emit. */
  days?: number;
  /** Start date (UTC) of epoch 0. */
  start?: Date;
  /** Baseline MRS around which the risk snapshot wanders. */
  mrs?: number;
  /** Continue an existing chain. */
  previous?: Receipt | null;
  startEpoch?: number;
  fwVersion?: string;
}

/** One machine-day of plausible operating context that satisfies the physics envelope. */
export function simulateContext(rng: () => number, taskClass: TaskClass, fw: string): ReceiptContext {
  const env = ENVELOPES[taskClass];
  const hours = taskClass === "idle" ? 0 : 6 + rng() * 14; // 6–20 h
  const seconds = Math.round(hours * 3600);
  const avgW = env.min_w + (0.25 + rng() * 0.5) * (env.max_w - env.min_w);
  const energy = seconds === 0 ? Math.round(rng() * env.idle_wh_max * 0.5) : Math.round((avgW * seconds) / 3600);
  const interventions = seconds > 0 && rng() < 0.15 ? 1 + Math.floor(rng() * 2) : 0;
  const fault = rng() < 0.08 ? [`F${Math.floor(100 + rng() * 900)}`] : [];
  return {
    task_class: taskClass,
    operating_seconds: seconds,
    energy_wh: energy,
    interventions,
    fault_codes: fault,
    fw_version: fw,
    env_severity: Math.round((0.2 + rng() * 0.4) * 100) / 100,
  };
}

/** Emit `days` hash-chained, signed receipts for one simulated machine. */
export function simulateMachine(opts: SimulateOptions = {}): { bundle: ReceiptBundle; keys: KeyPair } {
  const seed = opts.seed ?? 7;
  const rng = mulberry32(seed);
  const keys = opts.keys ?? generateKeyPair(`sim-${seed}`);
  const machineId = didKeyFromPublicKey(keys.publicKey);
  const taskClass = opts.taskClass ?? "amr_transport";
  const days = opts.days ?? 7;
  const start = opts.start ?? (opts.previous ? new Date(Date.parse(opts.previous.timestamp) + 1000) : new Date(Date.UTC(2026, 0, 1)));
  const fw = opts.fwVersion ?? "7.3.1";
  let mrs = opts.mrs ?? 720;
  let prev: Receipt | null = opts.previous ?? null;
  let epoch = opts.startEpoch ?? (prev ? prev.epoch + 1 : 0);
  const receipts: Receipt[] = [];
  for (let d = 0; d < days; d++) {
    const ctx = simulateContext(rng, taskClass, fw);
    const incident = ctx.fault_codes.length > 0 && ctx.interventions > 0;
    mrs = Math.max(300, Math.min(850, Math.round(mrs + (incident ? -35 : 2) + (rng() - 0.5) * 6)));
    const p = 1 / (1 + Math.exp((mrs - 560) / 45)); // illustrative monotone map for simulated snapshots
    const ts = new Date(start.getTime() + (d + 1) * 86_400_000 - 1000).toISOString();
    const r = createReceipt(
      {
        receipt_id: `rcpt_${machineId.slice(-6)}_${String(epoch).padStart(5, "0")}`,
        machine_id: machineId,
        epoch,
        timestamp: ts,
        event: incident ? "incident" : "operation",
        context: incident ? { ...ctx, note: "Fault with human intervention (simulated)" } : ctx,
        risk_snapshot: { mrs, p_fail_30: Math.round(p * 10_000) / 10_000, model: "simulated_snapshot" },
        attester: { id: machineId, kind: "device" },
      },
      keys.privateKey,
      prev,
    );
    receipts.push(r);
    prev = r;
    epoch++;
  }
  const bundle: ReceiptBundle = {
    version: POO_VERSION,
    machine_id: machineId,
    receipts,
    merkle_root: merkleRoot(receipts.map((r) => r.hash)),
    provenance: `SIMULATED — generated by @calibrum/poo simulateMachine(seed=${seed}, task=${taskClass}). Not field data.`,
  };
  return { bundle, keys };
}
